import { Dialog, DialogType, DialogFooter } from '@fluentui/react';  
import { PrimaryButton } from '@fluentui/react';  
import React, { useEffect, useRef } from "react"; 


interface TermsAndConditionsDialogProps {  
    isOpen: boolean;  
    onAccept: () => void;  
}  
  
const TermsAndConditionsDialog: React.FC<TermsAndConditionsDialogProps> = ({ isOpen, onAccept }) => {  

    const dialogTopRef = useRef<HTMLDivElement>(null);   
  
    useEffect(() => {  
        if (isOpen && dialogTopRef.current) {  
            dialogTopRef.current.scrollIntoView({ behavior: "smooth" });  
        }  
    }, [isOpen]);  

    return (  
        <Dialog  
            hidden={!isOpen}  
            onDismiss={() => {}} // provide a function that does nothing  
            dialogContentProps={{  
                type: DialogType.largeHeader,  
                title: 'PHOENIX GPT',  
                subText: ''  
            }}
            maxWidth={800}  
            modalProps={{  
                isBlocking: true, // make the dialog modal
                styles: { main: { maxHeight: 500 } }  
            }}  
        >  
         <div style={{
                    textAlign: "center"
                }}>
                <p>Terms of Use of PHOENIX Pharmahandel GmbH & Co KG for the internal AI chatbot (“PHOENIX GPT”)
                {"("}Version: 11.09.202{")"}
                </p>
            </div>
            <div>
                <p>
                <b>A.	PHOENIX Affiliate</b><br></br>
                {"("}1{")"}	The pre-condition for the usage of PHOENIX GPT is the registration of your employer {"("}PHOENIX Affiliate{")"} to this service. Costs of usage will be charged to PHOENIX Affiliate, proportional to actual usage and costs.<br></br><br></br>
                {"("}2{")"}	If you intend to use the PHOENIX GPT within a new service for customers or integrate the PHOENIX GPT into internal processes/systems etc., you must follow the local internal workflow regarding new services, IT systems etc. {"("}i.e., involve the relevant colleagues form IT, legal, data protection or information security{")"}. Please follow your local internal policies on handling with company data or company{"´"}s devices or systems.<br></br><br></br>
                {"("}3{")"}	The PHOENIX GPT is provided "as is"; there is no warranties or representations regarding its accuracy, reliability, or suitability for any particular purpose. The PHOENIX GPT may be subject to downtime or interruptions due to maintenance, upgrades, or other technical issues. PHOENIX is not liable for any damages or losses resulting from such downtime or interruptions.  PHOENIX reserves the right to modify or terminate the PHOENIX GPT at any time without notice. <br></br><br></br>
                <b>B.	Microsoft</b><br></br>
                Please note, that the sub-provider is Microsoft, i.e., you are using Azure OpenAI service.<br></br>
                </p>
                <p style={{
                    border: "1px solid black", padding: 5
                }}>
                Your prompts {"("}inputs{")"} and completions {"("}outputs{")"}, your embeddings, and your training data:<br></br><br></br>

                are NOT available to other Microsoft{"´"}s customers.<br></br>
                are NOT available to OpenAI.<br></br>
                are NOT used to improve OpenAI models.<br></br>
                are NOT used to improve any Microsoft or 3rd party products or services.<br></br>
                are NOT used for automatically improving Azure OpenAI models.<br></br><br></br>

                You can find more information <a href="https://learn.microsoft.com/en-us/legal/cognitive-services/openai/data-privacy">here.</a><br></br>
                </p>
                <p>
                    <b>C. 	Privacy Notice</b><br></br>
                    PHOENIX and PHOENIX Affiliate are so called Joint Controllers regarding the processing of user{"´"}s personal data. We are using your data processed for active directory account, so you as the user can get access to the PHOENIX GPT {"("}name, business e-mail address{")"}.<br></br><br></br>
                    Azure OpenAI processes the following types of data:<br></br>
                    prompts and generated content. Prompts are submitted by the user, and content is generated by the service, via the completions, chat completions, images and embeddings operations.<br></br>
                    <b>Please carefully read the last section of this Terms of Use on Abuse monitoring!</b><br></br><br></br>
                    Data processing is based on the employment or other contract with the user and on the legitimate interest of PHOENIX and PHOENIX Affiliate.<br></br>
                    PHOENIX has the admin rights; however, the user data are not used for the cost calculation.
                    Details on your rights related to data protection can be found in the privacy notice for employees or on PHOENIX website. The first contact point for you as user: <a href="mailto:dataprotection@phoenixgroup.eu">dataprotection@phoenixgroup.eu</a><br></br><br></br>
                    <b>D.	Use cases</b><br></br>
                    We encourage you to use the PHOENIX GPT. However, here are some considerations when choosing a use case:
                </p>
                <p style={{
                    border: "1px solid black", padding: 5
                }}>
                    <ul>
                        <li><b>Not suitable for open-ended</b>, unconstrained content generation. Scenarios where Users can generate content on any topic are more likely to produce offensive or harmful text. The same is true of longer generations.</li>
                        <li><b>Not suitable for scenarios where up-to-date, factually accurate information is crucial</b> unless you have human reviewers or are using the models to search your own documents and have verified suitability for your scenario. The service does not have information about events that occur after its training date, likely has missing knowledge about some topics, and may not always produce factually accurate information.</li>
                        <li><b>Avoid scenarios where use or misuse of the system could result in significant physical or psychological injury to an individual.</b> For example, scenarios that diagnose patients or prescribe medications have the potential to cause significant harm.</li>
                        <li><b>Avoid scenarios where use or misuse of the system could have a consequential impact on life opportunities or legal status.</b> Examples include scenarios where the AI system could affect an individual's legal status, legal rights, or their access to credit, education, employment, healthcare, housing, insurance, social welfare benefits, services, opportunities, or the terms on which they're provided.</li>
                        <li><b>Avoid high stakes scenarios that could lead to harm.</b> The models hosted by Azure OpenAI service reflect certain societal views, biases, and other undesirable content present in the training data or the examples provided in the prompt. As a result, we caution against using the models in high-stakes scenarios where unfair, unreliable, or offensive behaviour might be extremely costly or lead to harm.</li>
                        <li><b>Carefully consider use cases in high stakes domains or industry:</b> Examples include but are not limited to healthcare, medicine, finance, or legal.</li>
                        <li><b>Carefully consider well-scoped chatbot scenarios.</b> Limiting the use of the service in chatbots to a narrow domain reduces the risk of generating unintended or undesirable responses.</li>
                        <li><b>Carefully consider all generative use cases.</b> Content generation scenarios may be more likely to produce unintended outputs and these scenarios require careful consideration and mitigations.</li>
                    </ul>
                </p>
                <p>
                <b>E.   Recommended Usage</b><br></br>
                The PHOENIX GPT is designed to assist in general office work. It is not intended to provide medical, financial, or legal advice or replace the advice of a qualified professional. <b>The PHOENIX GPT is not a substitute for any professional advice.</b><br></br><br></br>
                The PHOENIX GPT responses are generated using the Open AI language model and may not always be accurate or complete. <b>The PHOENIX Affiliate and the user is responsible for implementing of a meaningful human oversight.</b><br></br><br></br>
                When using the PHOENIX GPT, the user is prohibited from any actions that violate applicable law, infringe the rights of third parties or violate the principles of the protection of minors. In particular, the following actions are prohibited:<br></br>
                <ul>
                    <li>the usage for pornographic and/or fraudulent content, services and/or products that violate youth protection laws, data protection laws and/or other laws;</li>
                    <li>the use, provision and distribution of content, services and/or products that are legally protected or encumbered with third-party rights {"("}e.g. copyrights, personality rights{")"} without being expressly entitled to do so;</li>
                </ul>
                You as the user must comply with the Microsoft Code of Conduct for the Open AI service: <br></br>
                <a href="https://learn.microsoft.com/en-us/legal/cognitive-services/openai/code-of-conduct?source=recommendations">https://learn.microsoft.com/en-us/legal/cognitive-services/openai/code-of-conduct?source=recommendations.</a><br></br><br></br>
                <b>F.   Abuse Monitoring</b><br></br><br></br>
                <b>
                Microsoft will temporarily store data submitted to the service, as well as output content, solely for debugging and to monitor for and prevent abusive or harmful uses or outputs of the service (for up to 30 days). Authorized Microsoft employees may review such data that has triggered the automated systems to investigate and verify potential abuse. For customers who have deployed Azure OpenAI service in the European Economic Area, the authorized Microsoft employees will be in the European Economic Area.<br></br><br></br>
                Please report problematic content to: <a href="mailto:ai@phoenixgroup.eu">ai@phoenixgroup.eu</a>
                </b><br></br><br></br><br></br>
                Please note, PHOENIX can change this Term of Use any time.
                </p>
             
            </div>  
            <DialogFooter>  
                <PrimaryButton onClick={onAccept} text="I Accept" />  
            </DialogFooter>  
        </Dialog>  
    );  
}  
  
export default TermsAndConditionsDialog;  
